package by.epam.tr.controller.command.ajax;

public enum AjaxCommandName {
    SHOW_CREW_MEMBERS, SHOW_FLIGHTS, CHECK_CREW_NAME, DELETE_CREW, DELETE_CREW_MEMBER, ADD_CREW_MEMBER, FIND_MAIN_PILOT, FIND_FREE_PLANE,
    FIND_COUNTRY_AIRPORT, FIND_FREE_DISPATCHER, CHECK_FLIGHT_NUMBER, SET_CREW_FOR_FLIGHT
}
